require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AtfcsController do

  # This should return the minimal set of attributes required to create a valid
  # Atfc. As you add validations to Atfc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cid" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AtfcsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all atfcs as @atfcs" do
      atfc = Atfc.create! valid_attributes
      get :index, {}, valid_session
      assigns(:atfcs).should eq([atfc])
    end
  end

  describe "GET show" do
    it "assigns the requested atfc as @atfc" do
      atfc = Atfc.create! valid_attributes
      get :show, {:id => atfc.to_param}, valid_session
      assigns(:atfc).should eq(atfc)
    end
  end

  describe "GET new" do
    it "assigns a new atfc as @atfc" do
      get :new, {}, valid_session
      assigns(:atfc).should be_a_new(Atfc)
    end
  end

  describe "GET edit" do
    it "assigns the requested atfc as @atfc" do
      atfc = Atfc.create! valid_attributes
      get :edit, {:id => atfc.to_param}, valid_session
      assigns(:atfc).should eq(atfc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Atfc" do
        expect {
          post :create, {:atfc => valid_attributes}, valid_session
        }.to change(Atfc, :count).by(1)
      end

      it "assigns a newly created atfc as @atfc" do
        post :create, {:atfc => valid_attributes}, valid_session
        assigns(:atfc).should be_a(Atfc)
        assigns(:atfc).should be_persisted
      end

      it "redirects to the created atfc" do
        post :create, {:atfc => valid_attributes}, valid_session
        response.should redirect_to(Atfc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved atfc as @atfc" do
        # Trigger the behavior that occurs when invalid params are submitted
        Atfc.any_instance.stub(:save).and_return(false)
        post :create, {:atfc => { "cid" => "invalid value" }}, valid_session
        assigns(:atfc).should be_a_new(Atfc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Atfc.any_instance.stub(:save).and_return(false)
        post :create, {:atfc => { "cid" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested atfc" do
        atfc = Atfc.create! valid_attributes
        # Assuming there are no other atfcs in the database, this
        # specifies that the Atfc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Atfc.any_instance.should_receive(:update).with({ "cid" => "1" })
        put :update, {:id => atfc.to_param, :atfc => { "cid" => "1" }}, valid_session
      end

      it "assigns the requested atfc as @atfc" do
        atfc = Atfc.create! valid_attributes
        put :update, {:id => atfc.to_param, :atfc => valid_attributes}, valid_session
        assigns(:atfc).should eq(atfc)
      end

      it "redirects to the atfc" do
        atfc = Atfc.create! valid_attributes
        put :update, {:id => atfc.to_param, :atfc => valid_attributes}, valid_session
        response.should redirect_to(atfc)
      end
    end

    describe "with invalid params" do
      it "assigns the atfc as @atfc" do
        atfc = Atfc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Atfc.any_instance.stub(:save).and_return(false)
        put :update, {:id => atfc.to_param, :atfc => { "cid" => "invalid value" }}, valid_session
        assigns(:atfc).should eq(atfc)
      end

      it "re-renders the 'edit' template" do
        atfc = Atfc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Atfc.any_instance.stub(:save).and_return(false)
        put :update, {:id => atfc.to_param, :atfc => { "cid" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested atfc" do
      atfc = Atfc.create! valid_attributes
      expect {
        delete :destroy, {:id => atfc.to_param}, valid_session
      }.to change(Atfc, :count).by(-1)
    end

    it "redirects to the atfcs list" do
      atfc = Atfc.create! valid_attributes
      delete :destroy, {:id => atfc.to_param}, valid_session
      response.should redirect_to(atfcs_url)
    end
  end

end
