require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AtfscsController do

  # This should return the minimal set of attributes required to create a valid
  # Atfsc. As you add validations to Atfsc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cid" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AtfscsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all atfscs as @atfscs" do
      atfsc = Atfsc.create! valid_attributes
      get :index, {}, valid_session
      assigns(:atfscs).should eq([atfsc])
    end
  end

  describe "GET show" do
    it "assigns the requested atfsc as @atfsc" do
      atfsc = Atfsc.create! valid_attributes
      get :show, {:id => atfsc.to_param}, valid_session
      assigns(:atfsc).should eq(atfsc)
    end
  end

  describe "GET new" do
    it "assigns a new atfsc as @atfsc" do
      get :new, {}, valid_session
      assigns(:atfsc).should be_a_new(Atfsc)
    end
  end

  describe "GET edit" do
    it "assigns the requested atfsc as @atfsc" do
      atfsc = Atfsc.create! valid_attributes
      get :edit, {:id => atfsc.to_param}, valid_session
      assigns(:atfsc).should eq(atfsc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Atfsc" do
        expect {
          post :create, {:atfsc => valid_attributes}, valid_session
        }.to change(Atfsc, :count).by(1)
      end

      it "assigns a newly created atfsc as @atfsc" do
        post :create, {:atfsc => valid_attributes}, valid_session
        assigns(:atfsc).should be_a(Atfsc)
        assigns(:atfsc).should be_persisted
      end

      it "redirects to the created atfsc" do
        post :create, {:atfsc => valid_attributes}, valid_session
        response.should redirect_to(Atfsc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved atfsc as @atfsc" do
        # Trigger the behavior that occurs when invalid params are submitted
        Atfsc.any_instance.stub(:save).and_return(false)
        post :create, {:atfsc => { "cid" => "invalid value" }}, valid_session
        assigns(:atfsc).should be_a_new(Atfsc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Atfsc.any_instance.stub(:save).and_return(false)
        post :create, {:atfsc => { "cid" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested atfsc" do
        atfsc = Atfsc.create! valid_attributes
        # Assuming there are no other atfscs in the database, this
        # specifies that the Atfsc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Atfsc.any_instance.should_receive(:update).with({ "cid" => "1" })
        put :update, {:id => atfsc.to_param, :atfsc => { "cid" => "1" }}, valid_session
      end

      it "assigns the requested atfsc as @atfsc" do
        atfsc = Atfsc.create! valid_attributes
        put :update, {:id => atfsc.to_param, :atfsc => valid_attributes}, valid_session
        assigns(:atfsc).should eq(atfsc)
      end

      it "redirects to the atfsc" do
        atfsc = Atfsc.create! valid_attributes
        put :update, {:id => atfsc.to_param, :atfsc => valid_attributes}, valid_session
        response.should redirect_to(atfsc)
      end
    end

    describe "with invalid params" do
      it "assigns the atfsc as @atfsc" do
        atfsc = Atfsc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Atfsc.any_instance.stub(:save).and_return(false)
        put :update, {:id => atfsc.to_param, :atfsc => { "cid" => "invalid value" }}, valid_session
        assigns(:atfsc).should eq(atfsc)
      end

      it "re-renders the 'edit' template" do
        atfsc = Atfsc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Atfsc.any_instance.stub(:save).and_return(false)
        put :update, {:id => atfsc.to_param, :atfsc => { "cid" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested atfsc" do
      atfsc = Atfsc.create! valid_attributes
      expect {
        delete :destroy, {:id => atfsc.to_param}, valid_session
      }.to change(Atfsc, :count).by(-1)
    end

    it "redirects to the atfscs list" do
      atfsc = Atfsc.create! valid_attributes
      delete :destroy, {:id => atfsc.to_param}, valid_session
      response.should redirect_to(atfscs_url)
    end
  end

end
